### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by kulakoff** [genieacs/genieacs-gui#104]
Hello,
after upgrading to new version from GIT is a problem with the launch genieacs gui.  Config file by default from git 

`

| roles = ['anonymous']     if current_user       roles.concat(Rails.configuration.users[current_user]['roles'])     end      @permissions \|\|= Rails.cache.fetch("#{roles}_permissions", race_condition_ttl: 5.seconds) do
-- | --
`

http://pix.toile-libre.org/upload/original/1544192256.png
```
root@cwmp:/opt/genieacs-gui-new/config# cat users.yml 
admin:
    password: admin
    roles: [admin]

user:
    password: user
    roles: [view]
root@cwmp:/opt/genieacs-gui-new/config# cat roles.yml 
anonymous:
    - [read, 1, /home]

admin:
    - [read, 1, /]
    - [create, 1, /]
    - [update, 1, /]
    - [delete, 1, /]

view:
    - [read, 1, /]
```
